### ISSUE TITLE
wrong bosh_exporter path in bosh-exporter-fix.yml

### ISSUE THREAD

**Issue by aad** [govau/deploy-prometheus#8]
/var/vcap/package should be /var/vcap/packages in below commit, its harmless but worth fixing

https://github.com/govau/deploy-prometheus/commit/9c8e3ac3e55b72f1a823a678b32503e07e9066d3#diff-51dce39be91bb7e83b8ca1baaaffeaa8R13

**Comment by gordcorp** [comment]
Thanks for reporting this @aad, it's fixed now.
